version: '2.1'
services:
    postgres:
        image: postgres:10
        environment:
            - POSTGRES_USER=esg_analytics
            - POSTGRES_PASSWORD=esg_analytics_password
            - POSTGRES_DB=esg_analytics
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - /home/data/pg_data:/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"